Sys.setenv("VROOM_CONNECTION_SIZE" = 131072*5)
library(stringr)
library(Seurat)
library(clusterProfiler)
library(patchwork)
library(dplyr)
library(org.Hs.eg.db)
library(tidyverse)
setwd("c:/Users/xjmik/Downloads/phaseI&phaseII_enzymes")
a<-list.files("c:/Users/xjmik/Downloads/phaseI&phaseII_enzymes")
d<-data.frame("Group","Symbol")
colnames(d)<-c("Group","Symbol")
for (i in 1:length(a)) {
  b<-read.csv(a[i],sep = ",",header = TRUE)
  c<-data.frame(rep(a[i],length(rownames(b))),b[,2])
  colnames(c)<-c("Group","Symbol")
  d<-rbind(d,c)
}
remove(a,i,b,c)
write.table(d,file = "c:/Users/xjmik/Desktop/detoxicity_sample.txt",sep = "\t")
